[package]
name = "stream-yolo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
glib = "0.20.7"
gstreamer = "0.23.3"
gstreamer-app = "0.23.3"
gstreamer-video = "0.23.3"
png = "0.17.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
yolo-rs = "0.1.1"
